### ISSUE TITLE
部署错误～

### ISSUE THREAD

**Issue by novioleo** [fanux/kubeinit#1]
大佬你好，我在release中下载了1.9.0的版本后在centos7上面进行初始化后然后apply -bie了之后出现了一些问题。
```bash
Loaded image: gcr.io/google_containers/pause-amd64:3.0
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/fanux/kubeinit/pkg.Apply()
	/usr/local/go/src/github.com/fanux/kubeinit/pkg/apply.go:278 +0x88c
github.com/fanux/kubeinit/cmd.glob..func1(0xa6d2e0, 0xc4200a2e00, 0x0, 0x1)
	/usr/local/go/src/github.com/fanux/kubeinit/cmd/apply.go:34 +0x6c
github.com/fanux/kubeinit/vendor/github.com/spf13/cobra.(*Command).execute(0xa6d2e0, 0xc4200a2dc0, 0x1, 0x1, 0xa6d2e0, 0xc4200a2dc0)
	/usr/local/go/src/github.com/fanux/kubeinit/vendor/github.com/spf13/cobra/command.go:565 +0x20d
github.com/fanux/kubeinit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa6d8e0, 0xc4200fe000, 0x0, 0x0)
	/usr/local/go/src/github.com/fanux/kubeinit/vendor/github.com/spf13/cobra/command.go:651 +0x2fe
github.com/fanux/kubeinit/vendor/github.com/spf13/cobra.(*Command).Execute(0xa6d8e0, 0xc4200ae008, 0xc420079f60)
	/usr/local/go/src/github.com/fanux/kubeinit/vendor/github.com/spf13/cobra/command.go:610 +0x2b
github.com/fanux/kubeinit/cmd.Execute()
	/usr/local/go/src/github.com/fanux/kubeinit/cmd/root.go:45 +0x31
main.main()
	/usr/local/go/src/github.com/fanux/kubeinit/main.go:45 +0x84

```

我是只有一个master，4个node，3个etcd。etcd在node上面。总共5台主机。
在执行的过程中master出了这个问题，其他的都没出现这个问题，请问这个怎么解决？

**Comment by fanux** [comment]
在out目录下看看各种配置生成的可正常，  主要原因应该是没有权限ssh到其它机器上。需要加--passwd参数，文档这块可能不太全。    不过那些配置生成了可以自己手动执行，compose文件，kubeadm config文件等  我还没完全整理完

**Comment by novioleo** [comment]
配置生成正常，compose的一些我还没看完。以为以前有过相关错误。

**Comment by fanux** [comment]
https://github.com/fanux/kubeinit/blob/master/cmd/apply.go#L57    这样配置密码  才能连接到别的机器上。   不过1.9这个可能有点问题，1.8.5应该可用

**Comment by novioleo** [comment]
我弄的ssh免密啊，还需要额外配置密码吗？

**Comment by fanux** [comment]
免密我没试过  我用了sshpass命令

**Comment by novioleo** [comment]
感恩大佬的回复。
